name: example
description: An example app to demonstrate the use of Acme Theme Importer
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: '>=3.0.4'

dependencies:
  flutter:
    sdk: flutter
  acme_theme:
    path: ../
  clean_framework: ^2.0.0-dev.0
  clean_framework_router: ^0.2.0-dev.2
  clean_framework_rest: ^0.2.0-dev.0
  logger: ^1.1.0
  sembast: ^3.3.0
  sembast_web: ^2.0.1+1
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  very_good_analysis: ^3.0.1

dependency_overrides:
  go_router: 5.1.2


flutter:
  uses-material-design: true

  assets:
    - assets/example-theme.acme
    - assets/themes/
    - assets/no_data.png
    - assets/icons/