name: acme_theme_example
description: An example app to demonstrate the use of Acme Theme Importer
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  acme_theme: ^0.6.0
  clean_framework: ^2.0.4
  clean_framework_rest: ^0.4.0
  clean_framework_router: ^0.4.0
  flutter_svg: ^1.1.6
  image_cropper: ^3.0.1
  image_picker: ^0.8.6+1
  json_theme: ^5.0.0
  logger: ^1.1.0
  path: '>=1.8.2 <2.0.0'
  path_provider: ^2.0.12
  sembast: ^3.4.0+6
  sembast_web: ^2.1.0+4
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  very_good_analysis: ^3.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/example-theme.acme
    - assets/themes/
    - assets/no_data.png
    - assets/icons/