name: example
description: An example app to demonstrate the use of Acme Theme Importer
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: '>=3.0.4'

dependencies:
  flutter:
    sdk: flutter
  acme_theme:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/example-theme.acme