name: acme_theme_example
description: An example app to demonstrate the use of Acme Theme Importer
publish_to: none
version: 2.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.19.6'

dependencies:
  flutter:
    sdk: flutter
  
  acme_theme:
    path: ../

  clean_framework: ^4.0.1
  clean_framework_router: ^0.5.10
  dio: ^5.8.0+1
  flutter_svg: ^2.1.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  json_theme: ^9.0.0+1
  logger: ^2.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sembast: ^3.8.5+1
  sembast_web: ^2.4.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/example-theme.acme
    - assets/themes/
    - assets/no_data.png
    - assets/icons/