name: acme_theme
description: A package to use the themes and components extracted from Acme Theme Builder.
version: 0.7.3
homepage: https://acmesoftware.com

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  http: ^1.0.0
  json_class: ^2.2.2
  json_theme: ^6.0.1+1
  meta: '>=1.8.0 <2.0.0'
  nsd: ^2.3.1
  path: '>=1.8.2 <2.0.0'
  path_provider: ^2.0.15
  shared_preferences: ^2.1.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1