name: acme_theme
description: A package to use the themes and components extracted from Acme Theme Builder.
version: 0.5.0
homepage: https://acmesoftware.com

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: '>=3.0.4'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  http: ^0.13.5
  json_class: ^2.1.2+13
  json_theme: ^4.0.3+1
  path: '>=1.8.2 <2.0.0'
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1