name: acme_theme
description: A package to use the themes and components extracted from Acme Theme Builder.
version: 0.8.2
homepage: https://acmesoftware.com

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.2'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.2
  json_class: ^3.0.1
  json_theme: ^7.0.0+1
  meta: '>=1.11.0 <2.0.0'
  nsd: ^4.0.3
  path: '>=1.9.0 <2.0.0'
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0